---
- name: Add chart repo for CSI driver for NFS
  kubernetes.core.helm_repository:
    name: csi-driver-nfs
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

- name: Install CSI driver for NFS
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref: csi-driver-nfs/csi-driver-nfs
    release_namespace: kube-system
    values:
      kubeletDir: /var/snap/microk8s/common/var/lib/kubelet

- name: Create a storage class for NFS server
  kubernetes.core.k8s:
    template: sc-nfs.yml.j2
