---
- name: Add chart repo for Grafana Loki
  kubernetes.core.helm_repository:
    name: grafana
    url: https://grafana.github.io/helm-charts

- name: Install Grafana Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    create_namespace: yes
    namespace: loki
    wait: false
    update_repo_cache: yes
    values:
      loki:
        commonConfig:
          replication_factor: 1
        storage:
          type: 'filesystem'
      singleBinary:
        replicas: 1
