---
# TODO
- name: Get script
  ansible.builtin.uri:
    url: https://get.docker.com
    return_content: true
  register: script

- name: Install docker
  ansible.builtin.shell:
    cmd: sh
    stdin: "{{ script.content }}"

- name: Enable to access docker with tcp
  community.general.ini_file:
    path: /usr/lib/systemd/system/docker.service
    section: Service
    option: ExecStart
    value: /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://192.168.3.10:2375
    backup: true

- name: Reload docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
    daemon-reload: true
